title: Andréa Duque
description: Notes on applied AI/ML, cloud native systems, and agentic AI.
baseurl: "/andreabrduque"
url: "https://andreabrduque.github.io"

theme: minima

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed

minima:
  skin: classic
